<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <WarningLevel>0</WarningLevel>
    <DefineConstants>TRACE;DEBUG;PREBUILD</DefineConstants>
    <NoWarn>
    </NoWarn>
    <UseVSHostingProcess>false</UseVSHostingProcess>
    <RunCodeAnalysis>false</RunCodeAnalysis>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <NoWarn>0169, 0162</NoWarn>
    <UseVSHostingProcess>false</UseVSHostingProcess>
    <DefineConstants>
    </DefineConstants>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup>
    <RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug Build CLI|x86'">
    <OutputPath>bin\x86\Debug Build CLI\</OutputPath>
    <DefineConstants>TRACE;DEBUG;PREBUILD</DefineConstants>
    <CodeAnalysisIgnoreBuiltInRuleSets>true</CodeAnalysisIgnoreBuiltInRuleSets>
    <CodeAnalysisIgnoreBuiltInRules>true</CodeAnalysisIgnoreBuiltInRules>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug Build CLI|AnyCPU'">
    <OutputPath>bin\Debug Build CLI\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="ICSharpCode.SharpZipLib">
      <HintPath>..\lib\ZLib\ICSharpCode.SharpZipLib.dll</HintPath>
    </Reference>
    <Reference Include="MiscUtil">
      <HintPath>..\lib\MiscUtil\MiscUtil.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\lib\Newtonsoft.Json\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="X360">
      <HintPath>..\lib\X360\X360.dll</HintPath>
    </Reference>
    <Reference Include="zlib.net">
      <HintPath>..\lib\ZLib\zlib.net.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Extensions\TreeViewBrowser.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\down.png" />
    <EmbeddedResource Include="Resources\left.png" />
    <EmbeddedResource Include="Resources\right.png" />
    <EmbeddedResource Include="Resources\up.png" />
    <EmbeddedResource Include="Resources\TreeViewOfd.ico" />
    <Content Include="RocksmithToolkitLib.TuningDefinition.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </Content>
    <Content Include="RocksmithToolkitLib.SongAppId.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Update="RocksmithToolkitLib.Config.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>True</Optimize>
  </PropertyGroup>
  <PropertyGroup>
    <PreBuildEvent Condition=" '$(OS)' == 'Unix' ">
      "$(SolutionDir)prebuild.sh" "$(ProjectDir)" "$(ProjectDir)ToolkitVersion.cs"
    </PreBuildEvent>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>
</Project>