<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>4</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>RocksmithToTabGUI.Program</StartupObject>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>logo.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestCertificateThumbprint>8098068DAE1FC64E74FCC62D70406D3AA01429B6</ManifestCertificateThumbprint>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestKeyFile>RocksmithToTabGUI_TemporaryKey.pfx</ManifestKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateManifests>true</GenerateManifests>
  </PropertyGroup>
  <PropertyGroup>
    <SignManifests>false</SignManifests>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>upgraded from .net framework 4.x to .net 8</PackageReleaseNotes>
    <FileVersion>1.2.0</FileVersion>
    <RepositoryUrl>https://github.com/fholger/RocksmithToTab</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/catara/rocksmith-custom-song-toolkit/tree/Main/lib/RocksmithToTab</PackageProjectUrl>
    <Copyright>original Copyright © Holger Frydrych 2016</Copyright>
    <Description>Program for saving Rocksmith notes in GuitarPro format</Description>
    <Authors>catara, Holger Frydrych</Authors>
    <Title>RocksmithToTabGUI</Title>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <OutputPath>bin\x86\Debug\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <OutputPath>bin\x86\Release\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="RocksmithToTabGUI_TemporaryKey.pfx" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RocksmithToTabLib\RocksmithToTabLib.csproj" />
    <ProjectReference Include="..\RocksmithToTab\RocksmithToTab.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="logo.ico" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.0">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4 %28x86 und x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Windows.Installer.4.5">
      <Visible>False</Visible>
      <ProductName>Windows Installer 4.5</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.DirectoryServices" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="._CallProgram.cs" />
    <Compile Remove="._CallProgram.Designer.cs" />
    <Compile Remove="._MainWindow.cs" />
    <Compile Remove="._MainWindow.Designer.cs" />
    <Compile Remove="._Program.cs" />
    <Compile Remove="._RocksmithLocator.cs" />
    <Compile Remove="Properties\._AssemblyInfo.cs" />
    <Compile Remove="Properties\._Resources.Designer.cs" />
    <Compile Remove="Properties\._Settings.Designer.cs" />
    <EmbeddedResource Remove="._CallProgram.resx" />
    <EmbeddedResource Remove="._MainWindow.resx" />
    <EmbeddedResource Remove="Properties\._Resources.resx" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="RocksmithToolkitLib">
      <HintPath>..\..\..\RocksmithTookitGUI\DLCManager\external_tools\RocksmithToolkitLib.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>