<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
    <Optimize>true</Optimize>
    <OutputPath>..\..\RocksmithTookitGUI\bin\Debug\</OutputPath>
    <DefineConstants>
    </DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
    <DebugType>none</DebugType>
    <OutputPath>..\..\RocksmithTookitGUI\bin\Release\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <NoWin32Manifest>true</NoWin32Manifest>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>CLI.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>convert2012.Program</StartupObject>
  </PropertyGroup>
  <PropertyGroup>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <OutputPath>..\..\RocksmithTookitGUI\bin\Release\</OutputPath>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="CLI.ico" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Properties\Resources.Designer.cs" />
  </ItemGroup>
  <PropertyGroup>
    <PostBuildEvent Condition=" '$(OS)' != 'Unix' ">
      (xcopy /S /Y "$(SolutionDir)Third-party Apps\Wwise\*" "$(TargetDir)Wwise\*" )
      (xcopy /S /Y "$(SolutionDir)Third-party Apps\ogg*.*" "$(TargetDir)" )
      (xcopy /S /Y "$(SolutionDir)Third-party Apps\nvdxt.exe" "$(TargetDir)" )
      (xcopy /S /Y "$(SolutionDir)Third-party Apps\packed_codebook*.*" "$(TargetDir)" )
      (xcopy /S /Y "$(SolutionDir)Third-party Apps\revorb.exe" "$(TargetDir)" )
      (xcopy /S /Y "$(SolutionDir)Third-party Apps\ww2ogg.exe" "$(TargetDir)" )
      (xcopy /S /Y "$(SolutionDir)Third-party Apps\*.xml" "$(TargetDir)" )
      (rd /s /q "$(TargetDir)ddc")
    </PostBuildEvent>
    <PostBuildEvent Condition=" '$(OS)' == 'Unix' ">
      cp -Rf "$(SolutionDir)Third-party Apps/Wwise/" "$(TargetDir)Wwise\" ;
      cp -Rf "$(SolutionDir)Third-party Apps/ogg*" "$(TargetDir)" ;
      cp -Rf "$(SolutionDir)Third-party Apps/nvdxt.exe" "$(TargetDir)" ;
      cp -Rf "$(SolutionDir)Third-party Apps/packed_codebook*" "$(TargetDir)" ;
      cp -Rf "$(SolutionDir)Third-party Apps/revorb.exe" "$(TargetDir)" ;
      cp -Rf "$(SolutionDir)Third-party Apps/ww2ogg.exe" "$(TargetDir)" ;
      cp -Rf "$(SolutionDir)Third-party Apps/*.xml" "$(TargetDir)" ;
      rm -rf  "$(TargetDir)ddc"
    </PostBuildEvent>
  </PropertyGroup>
  <PropertyGroup>
    <PostBuildEvent>REM copy support files
xcopy /E /S /Y "$(SolutionDir)ThirdPartyApps\*.*" "$(TargetDir)*.*"</PostBuildEvent>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="RocksmithToolkitLib">
      <HintPath>..\..\RocksmithToolkitLib\bin\Release\net7.0-windows10.0.22621.0\RocksmithToolkitLib.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
</Project>