<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>RocksmithToTabLib</AssemblyTitle>
    <Product>RocksmithToTabLib</Product>
    <Copyright>original Copyright © Holger Frydrych 2016</Copyright>
    <Version>1.2.0</Version>
    <Authors>catara, Holger Frydrych</Authors>
    <Description>library for saving Rocksmith notes in GuitarPro format</Description>
    <PackageProjectUrl>https://github.com/catara/rocksmith-custom-song-toolkit/tree/Main/lib/RocksmithToTab</PackageProjectUrl>
    <RepositoryUrl>https://github.com/fholger/RocksmithToTab</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>upgraded from .net framework 4.x to .net 8</PackageReleaseNotes>
    <Title>RocksmithToTabLib</Title>
    <IncludeSymbols>False</IncludeSymbols>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <OutputPath>bin\Debug\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <OutputPath>bin\Release\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.6.0-preview3.19128.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="._Converter.cs" />
    <Compile Remove="._GP5File.cs" />
    <Compile Remove="._Gpif.cs" />
    <Compile Remove="._GpxContainer.cs" />
    <Compile Remove="._GpxExporter.cs" />
    <Compile Remove="._PSARC.cs" />
    <Compile Remove="._PSARCBrowser.cs" />
    <Compile Remove="._RhythmDetector.cs" />
    <Compile Remove="._Score.cs" />
    <Compile Remove="._VersionInfo.cs" />
    <Compile Remove="Properties\._AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="www.rocksmithtotab.de" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="RocksmithToolkitLib">
      <HintPath>..\..\..\RocksmithTookitGUI\DLCManager\external_tools\RocksmithToolkitLib.dll</HintPath>
    </Reference>
    <Reference Include="X360">
      <HintPath>..\..\..\RocksmithTookitGUI\DLCManager\external_tools\X360.dll</HintPath>
    </Reference>
    <Reference Include="zlib.net">
      <HintPath>..\..\ZLib\zlib.net.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>