<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
    <Optimize>true</Optimize>
    <OutputPath>..\..\RocksmithTookitGUI\bin\Debug\</OutputPath>
    <DefineConstants>
    </DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
    <DebugType>none</DebugType>
    <OutputPath>..\..\RocksmithTookitGUI\bin\Release\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>CLI.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <NoWin32Manifest>true</NoWin32Manifest>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <OutputPath>..\..\RocksmithTookitGUI\bin\Release\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>ArtistFolderCreator.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="CLI.ico" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Properties\Resources.Designer.cs" />
  </ItemGroup>
  <PropertyGroup />
</Project>