<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
    <Optimize>true</Optimize>
    <OutputPath>..\..\RocksmithTookitGUI\bin\Debug\</OutputPath>
    <DefineConstants>
    </DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
    <DebugType>none</DebugType>
    <OutputPath>..\..\RocksmithTookitGUI\bin\Release\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>CLI.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>packagecreator.Program</StartupObject>
  </PropertyGroup>
  <PropertyGroup>
    <NoWin32Manifest>true</NoWin32Manifest>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <OutputPath>..\..\RocksmithTookitGUI\bin\Release\</OutputPath>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="NDesk.Options">
      <HintPath>..\..\lib\NDesk\NDesk.Options.dll</HintPath>
    </Reference>
    <Reference Include="RocksmithToolkitLib">
      <HintPath>..\..\RocksmithToolkitLib\bin\Release\net7.0-windows10.0.22621.0\RocksmithToolkitLib.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="CLI.ico" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Properties\Resources.Designer.cs" />
  </ItemGroup>
</Project>